name: 'chromatic should deploy'
description: 'Checks if storybook build changed from previous commit  '
author: 'fddayan'
branding:
  icon: 'alert-triangle'  
  color: 'green'
inputs:
  artifactName:
    required: true  
    description: "The artifact name to store"
  previousSha:
    required: false
    description: "Previous sha commit to checkout to build storybook in case artifact is not present."
    default: ${{github.event.before}}
  GITHUB_TOKEN:
    description: 'The GitHub access token (e.g. secrets.GITHUB_TOKEN) used to create or update the comment. This defaults to {{ github.token }}.'
    default: '${{ github.token }}'
    required: false
  storybookBuildCommand:
    description: Command to run to build storybook.
    required: false
    default: npm run build-storybook
  debug:
    description: 'if set to true it will upload the output of storybook build as artifacts.'    
    required: false
    default: false
  checkoutRepoFolder:
    description: 'The folder to checkout the second repository with the previous commit to build Storybook' 
    required: false
    default: 'previous'
  storybookStaticDir:
    description: 'Output build directory for Storybook'
    required: false
    default: 'storybook-static'
  artifactWorkflow:
    description: 'Workflow to look for artifacts uploaded by this action'
    required: true
  artifactBranch:
    description: 'The branch to look for artifacts uploaded by this action'
    required: false
    default: ${{ github.event.pull_request.head.ref }}
  artifactDownloadPath:
    description: 'The path to download the artifacts uploaded by this action'
    required: false
    default: 'storybook-hash'
  forceDeploy:
    description: 'forces a deploy to Chromatic'
    required: false
    default: false
outputs:
  shouldDeploy:
    description: TRUE/FALSE value if it should deploy chromatic based on previous build
    value: ${{ steps.chromatic-checker.outputs.shouldDeploy }}

runs:
  using: 'composite'
  steps:    
    - name: Download artifact with previous storybook build hash
      if: ${{inputs.forceDeploy == 'false'}}
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{inputs.GITHUB_TOKEN}}
        workflow: ${{inputs.artifactWorkflow}}
        branch: ${{inputs.artifactBranch}}
        name: ${{inputs.artifactName}}
        path: ${{inputs.artifactDownloadPath}}
        workflow_conclusion: false
        check_artifacts: true
        search_artifacts: true
    - name: Checks previous artifact existence
      id: previous_artifact
      uses: andstor/file-existence-action@v2.0.0
      with:
        files: "${{inputs.artifactDownloadPath}}/storybook-hash-current.txt"
    - uses: actions/checkout@v2
      if: ${{steps.previous_artifact.outputs.files_exists == 'false'}}
      with:
        clean: false
        fetch-depth: 0
        path: ${{inputs.checkoutRepoFolder}}
        ref: ${{inputs.previousSha}}
    - name: Build Storybook in previous build
      if: ${{steps.previous_artifact.outputs.files_exists == 'false'}}
      run: ${{inputs.storybookBuildCommand}} > build-storybook-previous.log 2>&1
      working-directory: ${{inputs.checkoutRepoFolder}}
      shell: bash
    - name: Build Storybook in current build
      run: ${{inputs.storybookBuildCommand}} > build-storybook-current.log 2>&1
      shell: bash
    - name: Upload previous storybook build output
      if: ${{inputs.debug == 'true' && steps.previous_artifact.outputs.files_exists == 'false'}}
      uses: actions/upload-artifact@v2
      with:
        name: ${{inputs.artifactName}}-storybook-build-previous
        path: build-storybook-previous.log
    - name: Upload current storybook build output
      if: ${{inputs.debug == 'true'}}
      uses: actions/upload-artifact@v2
      with:
        name: ${{inputs.artifactName}}-storybook-build-current
        path: build-storybook-current.log
    - name: Generate hash for previous commit from current storybook build
      if: ${{steps.previous_artifact.outputs.files_exists == 'false'}}
      run: |
        mkdir -p ${{inputs.artifactDownloadPath}}
        find ${{inputs.checkoutRepoFolder}}/${{inputs.storybookStaticDir}} -type f -exec md5sum {} \; | md5sum > ${{inputs.artifactDownloadPath}}/storybook-hash-current.txt
      shell: bash
    - name: Get hash values for previous and current storybook builds
      id: storybook-hash
      run: |          
         find ${{inputs.storybookStaticDir}} -type f -exec md5sum {} \; | md5sum > storybook-hash-current.txt
         echo "::set-output name=previous_hash::$(cat ${{inputs.artifactDownloadPath}}/storybook-hash-current.txt)"
         echo "::set-output name=current_hash::$(cat storybook-hash-current.txt)"
      shell: bash
    - name: Archive current Storybook build hash
      uses: actions/upload-artifact@v2
      with:
        name: ${{inputs.artifactName}}
        path: storybook-hash-current.txt
    - name: Print info
      run: |
        echo "Previous hash: ${{ steps.storybook-hash.outputs.previous_hash}}"
        echo "Current hash: ${{steps.storybook-hash.outputs.current_hash }}"
        echo "Should deploy: ${{ steps.storybook-hash.outputs.previous_hash != steps.storybook-hash.outputs.current_hash }}"
        echo "Artifact found: ${{steps.previous_artifact.outputs.files_exists}}"
      shell: bash
    - run: echo "::set-output name=shouldDeploy::${{ steps.storybook-hash.outputs.previous_hash != steps.storybook-hash.outputs.current_hash }}"
      id: chromatic-checker
      shell: bash
